# Generated by Django 5.1.5 on 2025-02-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name_plural': 'Charities'},
        ),
    ]
