# Generated by Django 5.1.5 on 2025-02-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_charity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationallocation',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='donationallocation',
            name='charity',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='DonationAllocation',
        ),
    ]
